default_stages: [ pre-commit ]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.2
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.0
  #   hooks:
  #     # Run the type checker
  #     - id: mypy
  #       types_or: [ python, pyi, jupyter ]
  #       additional_dependencies:
  #         - "pydantic>=1.10.4"
  #         - ujson
  #         - types-ujson
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.2
    hooks:
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-conventional' ]