services:
  budapp-postgres:
    image: postgres
    restart: always
    container_name: bud-serve-$NAMESPACE-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER must be set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB must be set}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - budapp-db-data:/var/lib/postgresql/data
    networks:
      - bud-microframe-nw
  budapp-pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: bud-serve-$NAMESPACE-pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?PGADMIN_DEFAULT_EMAIL must be set}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:?PGADMIN_DEFAULT_PASSWORD must be set}
    volumes:
      - budapp-pgadmin-data:/var/lib/pgadmin
    networks:
      - bud-microframe-nw
    depends_on:
      - budapp-postgres

volumes:
  budapp-db-data:
  budapp-pgadmin-data:
