include:
  - ./docker-compose-redis.yaml
  - ./docker-compose-postgres.yaml

services:
  app:
    image: bud-microframe/$APP_NAME:$NAMESPACE
    container_name: bud-mf-$NAMESPACE-$APP_NAME
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    # command: [ "uvicorn", "$APP_NAME.main:app", "--host", "0.0.0.0", "--port", $APP_PORT ]
    command: [ "sh", "/app/startup.sh" ]
    ports:
      - "$DAPR_GRPC_PORT:$DAPR_GRPC_PORT" # Dapr instances communicate over gRPC so gRPC port needs to be exposed
      - "$DAPR_HTTP_PORT:$DAPR_HTTP_PORT" # Expose Dapr HTTP port for service invocation
      - "$APP_PORT:$APP_PORT" # Expose app port for debugging purposes
    volumes:
      - ../:/app/
    env_file:
      - path: ../.env
        required: true
    depends_on:
      - redis
      - placement
      - postgres
    networks:
      - bud-microframe-nw
  sidecar:
    container_name: bud-mf-$NAMESPACE-$APP_NAME-dapr
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "$APP_NAME",
      "--app-port", "$APP_PORT",
      "--dapr-http-port", "$DAPR_HTTP_PORT",
      "--dapr-grpc-port", "$DAPR_GRPC_PORT",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--resources-path", "/components",
      "--config", "/config/appconfig.yaml",
      "--log-as-json"
    ]
    env_file:
      - path: ../.env
        required: true
    volumes:
      - "${DAPR_COMPONENTS:-../.dapr/components/}:/components" # Mount the components folder for the runtime to use. The mounted location must match the --resources-path argument.
      - "${DAPR_APP_CONFIG:-../.dapr/appconfig-dev.yaml}:/config/appconfig.yaml" # Mount the config file for the runtime to use. The mounted location must match the --config argument.
    depends_on:
      - app
    network_mode: "service:app" # Attach the sidecar service to the app network namespace
  placement:
    container_name: bud-mf-$NAMESPACE-placement
    image: "daprio/placement:edge"
    command: [ "./placement", "--port", "50006" ]
    ports:
      - "50006:50006"

networks:
  bud-microframe-nw:
    name: bud-microframe-$NAMESPACE
