services:
  postgres:
    image: postgres
    restart: always
    container_name: bud-mf-$NAMESPACE-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER must be set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB must be set}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bud-microframe-nw
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: bud-mf-$NAMESPACE-pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?PGADMIN_DEFAULT_EMAIL must be set}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:?PGADMIN_DEFAULT_PASSWORD must be set}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - bud-microframe-nw
    depends_on:
      - postgres

volumes:
  db-data:
  pgadmin-data:
