apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cluster-recommended-scheduler
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 24h" # Every 24 hours 
  - name: direction
    value: "input"
  - name: route
    value: "/clusters/recommended-scheduler"