# Reference: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-redis-pubsub/

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-redis
  namespace: development
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      secretKeyRef:
        name: REDIS_URI
        key: REDIS_URI
    - name: redisPassword
      secretKeyRef:
        name: REDIS_PASSWORD
        key: REDIS_PASSWORD
    - name: consumerID
      value: "{appID}"
    - name: concurrency
      value: "10"
auth:
  secretStore: secretstore-local
