# Reference: https://docs.dapr.io/reference/components-reference/supported-secret-stores/file-secret-store/

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore-local
  namespace: development
spec:
  type: secretstores.local.env
  version: v1
  metadata:
    - name: prefix
      value: "SECRETS_"