# Reference: https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: development
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      secretKeyRef:
        name: REDIS_URI
        key: REDIS_URI
    - name: redisPassword
      secretKeyRef:
        name: REDIS_PASSWORD
        key: REDIS_PASSWORD
    - name: actorStateStore
      value: "true"
auth:
  secretStore: secretstore-local