apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: pubsub-subscription
spec:
  topic: budAppMessages
  routes:
    rules:
      - match: event.type == "credential_update"
        path: /credentials/update
    default: /notifications
  pubsubname: pubsub-redis
  deadLetterTopic: poisonMessages
scopes:
  - budapp