name: Build and Push Nightly Docker Image

on:
  push:
    branches:
      - main

jobs:
  lint-test-secure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit black pytest

      - name: Run flake8 (linting)
        continue-on-error: true
        run: flake8 .

      - name: Run black (format check)
        continue-on-error: true
        run: black --check .

      - name: Run bandit (security check)
        continue-on-error: true
        run: bandit -r . -x tests

      - name: Run tests
        continue-on-error: true
        run: pytest

  build-and-push:
    needs: lint-test-secure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./deploy/Dockerfile
          tags: budstudio/budapp:nightly
