"""Cloud Model, Endpoint Table Updated

Revision ID: 006234a6eb89
Revises: 235cab970030
Create Date: 2025-05-19 08:04:52.419757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006234a6eb89'
down_revision: Union[str, None] = '235cab970030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_model', sa.Column('deprecation_date', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint("cloud_model_uri_key", 'cloud_model', ['uri'])
    op.add_column('endpoint', sa.Column('is_deprecated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint', 'is_deprecated')
    op.drop_constraint("cloud_model_uri_key", 'cloud_model', type_='unique')
    op.drop_column('cloud_model', 'deprecation_date')
    # ### end Alembic commands ###
