"""added template model.

Revision ID: 036fd90d4d6b
Revises: d5d05bae8c2c
Create Date: 2024-11-14 10:20:47.850438

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "036fd90d4d6b"
down_revision: Union[str, None] = "d5d05bae8c2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_template",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column(
            "template_type",
            sa.Enum(
                "summarization",
                "chat",
                "question_answering",
                "rag",
                "code_gen",
                "code_translation",
                "entity_extraction",
                "sentiment_analysis",
                "document_analysis",
                name="template_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("avg_sequence_length", sa.Integer(), nullable=True),
        sa.Column("avg_context_length", sa.Integer(), nullable=True),
        sa.Column("per_session_tokens_per_sec", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("ttft", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("e2e_latency", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_template")),
        sa.UniqueConstraint("template_type", name=op.f("uq_model_template_template_type")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_template")
    # ### end Alembic commands ###
