"""added status to project table.

Revision ID: 04ef4a274216
Revises: cbbdd257bedd
Create Date: 2024-12-18 10:16:17.791188

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "04ef4a274216"
down_revision: Union[str, None] = "cbbdd257bedd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("active", "deleted", name="project_status_enum").create(op.get_bind())
    op.add_column(
        "project",
        sa.Column(
            "status",
            postgresql.ENUM("active", "deleted", name="project_status_enum", create_type=False),
            nullable=False,
        ),
    )
    op.drop_column("project", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("project", "status")
    sa.Enum("active", "deleted", name="project_status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
