"""added active replicas to endpoint table.

Revision ID: 0618df5dc3b3
Revises: 197143f29114
Create Date: 2025-01-29 12:54:51.810218

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0618df5dc3b3"
down_revision: Union[str, None] = "197143f29114"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoint", sa.Column("active_replicas", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("endpoint", "active_replicas")
    # ### end Alembic commands ###
