"""removed is active from endpint table.

Revision ID: 0c7fdc4b7072
Revises: 892c31d1e086
Create Date: 2024-12-23 11:55:08.540869

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0c7fdc4b7072"
down_revision: Union[str, None] = "892c31d1e086"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("endpoint", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoint", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
