"""updated message table.

Revision ID: 1003edcadb5d
Revises: 19fcbbcc98ca
Create Date: 2025-02-28 13:32:43.431142

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "1003edcadb5d"
down_revision: Union[str, None] = "19fcbbcc98ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("upvote", "downvote", name="feedback_enum").create(op.get_bind())
    op.add_column(
        "messages",
        sa.Column(
            "feedback", postgresql.ENUM("upvote", "downvote", name="feedback_enum", create_type=False), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "feedback")
    sa.Enum("upvote", "downvote", name="feedback_enum").drop(op.get_bind())
    # ### end Alembic commands ###
