"""Removed Register from cluster.

Revision ID: 1a20ca43ac69
Revises: 375eb22cb3af
Create Date: 2025-01-10 06:14:24.322892

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference


# revision identifiers, used by Alembic.
revision: str = "1a20ca43ac69"
down_revision: Union[str, None] = "375eb22cb3af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="cluster_status_enum",
        new_values=["available", "not_available", "error", "deleting", "deleted"],
        affected_columns=[TableReference(table_schema="public", table_name="cluster", column_name="status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="cluster_status_enum",
        new_values=["available", "not_available", "registering", "error", "deleting", "deleted"],
        affected_columns=[TableReference(table_schema="public", table_name="cluster", column_name="status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
