"""Tag added in worflow.

Revision ID: 1b33efcd5611
Revises: da9cd25f9dcc
Create Date: 2025-01-01 05:48:11.955993

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1b33efcd5611"
down_revision: Union[str, None] = "da9cd25f9dcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow", sa.Column("tag", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow", "tag")
    # ### end Alembic commands ###
