"""Updated modality Enum.

Revision ID: 2278bdce773d
Revises: 20d36fea791f
Create Date: 2025-04-16 13:38:59.419592

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference


# revision identifiers, used by Alembic.
revision: str = "2278bdce773d"
down_revision: Union[str, None] = "20d36fea791f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="modality_enum",
        new_values=[
            "llm",
            "mllm",
            "image",
            "embedding",
            "text_to_speech",
            "speech_to_text",
            "llm_embedding",
            "mllm_embedding",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="cloud_model", column_name="modality"),
            TableReference(table_schema="public", table_name="model", column_name="modality"),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="modality_enum",
        new_values=["llm", "mllm", "image", "embedding", "text_to_speech", "speech_to_text"],
        affected_columns=[
            TableReference(table_schema="public", table_name="cloud_model", column_name="modality"),
            TableReference(table_schema="public", table_name="model", column_name="modality"),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
