"""Modified Provider Type As Unique

Revision ID: 235cab970030
Revises: 5c952f6e6d36
Create Date: 2025-05-19 05:37:35.662965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235cab970030'
down_revision: Union[str, None] = '5c952f6e6d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("provider_type_key", 'provider', ['type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("provider_type_key", 'provider', type_='unique')
    # ### end Alembic commands ###
