"""added status to project table

Revision ID: 27a44af3fdfe
Revises: b15331009e3f
Create Date: 2024-12-16 09:55:02.458803

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "27a44af3fdfe"
down_revision: Union[str, None] = "4d5cd5449049"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("active", "deleted", name="project_status_enum").create(op.get_bind())
    op.add_column(
        "project",
        sa.Column(
            "status",
            postgresql.ENUM("active", "deleted", name="project_status_enum", create_type=False),
            nullable=False,
        ),
    )
    op.drop_column("project", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("project", "status")
    sa.Enum("active", "deleted", name="project_status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
