"""Updated cluster table.

Revision ID: 2ce2068d3257
Revises: 036fd90d4d6b
Create Date: 2024-11-18 03:58:47.083974

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "2ce2068d3257"
down_revision: Union[str, None] = "036fd90d4d6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("ingress_url", sa.String(), nullable=False))
    op.add_column("cluster", sa.Column("cpu_count", sa.Integer(), nullable=False))
    op.add_column("cluster", sa.Column("gpu_count", sa.Integer(), nullable=False))
    op.add_column("cluster", sa.Column("hpu_count", sa.Integer(), nullable=False))
    op.add_column("cluster", sa.Column("cpu_total_workers", sa.Integer(), nullable=False))
    op.add_column("cluster", sa.Column("cpu_available_workers", sa.Integer(), nullable=False))
    op.add_column("cluster", sa.Column("gpu_total_workers", sa.Integer(), nullable=False))
    op.add_column("cluster", sa.Column("gpu_available_workers", sa.Integer(), nullable=False))
    op.add_column("cluster", sa.Column("hpu_total_workers", sa.Integer(), nullable=False))
    op.add_column("cluster", sa.Column("hpu_available_workers", sa.Integer(), nullable=False))
    op.drop_column("cluster", "type")
    op.drop_column("cluster", "configuration")
    op.drop_column("cluster", "total_workers")
    op.drop_column("cluster", "core_count")
    op.drop_column("cluster", "kube_nodes")
    op.drop_column("cluster", "host")
    op.drop_column("cluster", "used_workers")
    op.drop_column("cluster", "available_workers")
    op.drop_column("cluster", "kubernetes_metadata")
    op.drop_column("cluster", "enable_master_node")
    op.drop_column("cluster", "platform")
    op.drop_column("cluster", "threads_per_core")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("threads_per_core", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "cluster",
        sa.Column(
            "platform",
            postgresql.ENUM("kubernetes", "openshift", name="cluster_platform_enum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("cluster", sa.Column("enable_master_node", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column("cluster", sa.Column("kubernetes_metadata", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("cluster", sa.Column("available_workers", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("cluster", sa.Column("used_workers", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("cluster", sa.Column("host", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("cluster", sa.Column("kube_nodes", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("cluster", sa.Column("core_count", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("cluster", sa.Column("total_workers", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("cluster", sa.Column("configuration", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column(
        "cluster",
        sa.Column(
            "type", postgresql.ENUM("cpu", "gpu", "hpu", name="cluster_type_enum"), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("cluster", "hpu_available_workers")
    op.drop_column("cluster", "hpu_total_workers")
    op.drop_column("cluster", "gpu_available_workers")
    op.drop_column("cluster", "gpu_total_workers")
    op.drop_column("cluster", "cpu_available_workers")
    op.drop_column("cluster", "cpu_total_workers")
    op.drop_column("cluster", "hpu_count")
    op.drop_column("cluster", "gpu_count")
    op.drop_column("cluster", "cpu_count")
    op.drop_column("cluster", "ingress_url")
    # ### end Alembic commands ###
