"""modified endpoint and cluster table.

Revision ID: 33225f9cc055
Revises: 28422b983323
Create Date: 2025-03-14 13:11:53.342345

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "33225f9cc055"
down_revision: Union[str, None] = "28422b983323"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("total_nodes", sa.Integer(), nullable=False))
    op.add_column("cluster", sa.Column("available_nodes", sa.Integer(), nullable=False))
    op.add_column("endpoint", sa.Column("node_list", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("endpoint", "node_list")
    op.drop_column("cluster", "available_nodes")
    op.drop_column("cluster", "total_nodes")
    # ### end Alembic commands ###
