"""Add deployment_settings column to endpoint table

Revision ID: 34c89ff1662c
Revises: 647128ba2f4d
Create Date: 2025-07-24 17:59:39.682574

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "34c89ff1662c"
down_revision: Union[str, None] = "647128ba2f4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoint", sa.Column("deployment_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("endpoint", "deployment_settings")
    # ### end Alembic commands ###
