"""added model_status to model and cloud model table

Revision ID: 3518c477e692
Revises: 5352d4677f70
Create Date: 2024-12-12 07:28:43.276882

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3518c477e692"
down_revision: Union[str, None] = "b15331009e3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("active", "deleted", name="status_enum").create(op.get_bind())
    op.add_column(
        "cloud_model",
        sa.Column(
            "model_status", postgresql.ENUM("active", "deleted", name="status_enum", create_type=False), nullable=False
        ),
    )
    op.drop_column("cloud_model", "is_active")
    op.add_column(
        "model",
        sa.Column(
            "model_status", postgresql.ENUM("active", "deleted", name="status_enum", create_type=False), nullable=False
        ),
    )
    op.drop_column("model", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("model", "model_status")
    op.add_column("cloud_model", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("cloud_model", "model_status")
    sa.Enum("active", "deleted", name="status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
