"""d ataset-sync-table

Revision ID: 353f7374f870
Revises: fd8b19e0a305
Create Date: 2025-07-04 04:04:15.117160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '353f7374f870'
down_revision: Union[str, None] = 'fd8b19e0a305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_sync_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manifest_version', sa.String(length=50), nullable=False),
    sa.Column('sync_timestamp', sa.String(), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eval_sync_state')
    # ### end Alembic commands ###
