"""Updated Endpoint Table.

Revision ID: 375eb22cb3af
Revises: af5cc669f51e
Create Date: 2025-01-04 10:23:34.365587

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference


# revision identifiers, used by Alembic.
revision: str = "375eb22cb3af"
down_revision: Union[str, None] = "af5cc669f51e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="endpoint_status_enum",
        new_values=["running", "failure", "deploying", "unhealthy", "deleting", "deleted", "pending"],
        affected_columns=[TableReference(table_schema="public", table_name="endpoint", column_name="status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="endpoint_status_enum",
        new_values=["running", "failure", "deploying", "unhealthy", "deleting", "deleted"],
        affected_columns=[TableReference(table_schema="public", table_name="endpoint", column_name="status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
