"""Modified Field In Model.

Revision ID: 40a8d774f38f
Revises: 1d94eee5d3f2
Create Date: 2024-10-26 13:29:22.280647

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "40a8d774f38f"
down_revision: Union[str, None] = "1d94eee5d3f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model", sa.Column("created_by", sa.Uuid(), nullable=False))
    op.create_foreign_key(op.f("fk_model_created_by_user"), "model", "user", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_model_created_by_user"), "model", type_="foreignkey")
    op.drop_column("model", "created_by")
    # ### end Alembic commands ###
