"""Updated model table.

Revision ID: 42e713425e99
Revises: acb041e05c53
Create Date: 2024-11-27 04:43:42.175004

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "42e713425e99"
down_revision: Union[str, None] = "acb041e05c53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model", sa.Column("local_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model", "local_path")
    # ### end Alembic commands ###
