"""Add faqs column to model_licenses

Revision ID: 45744566ecee
Revises: 7420487c5f37
Create Date: 2024-11-06 09:34:14.695841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45744566ecee'
down_revision: Union[str, None] = '7420487c5f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_licenses', sa.Column('faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_licenses', 'faqs')
    # ### end Alembic commands ###
