"""Updated license table.

Revision ID: 4b0889f0c7bf
Revises: 39c0195636ca
Create Date: 2025-04-01 03:32:20.370940

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4b0889f0c7bf"
down_revision: Union[str, None] = "39c0195636ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_licenses", sa.Column("license_type", sa.String(), nullable=True))
    op.add_column("model_licenses", sa.Column("description", sa.String(), nullable=True))
    op.add_column("model_licenses", sa.Column("suitability", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_licenses", "suitability")
    op.drop_column("model_licenses", "description")
    op.drop_column("model_licenses", "license_type")
    # ### end Alembic commands ###
