"""Cluster Status Update.

Revision ID: 4d5cd5449049
Revises: b15331009e3f
Create Date: 2024-12-16 03:20:23.743431

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference


# revision identifiers, used by Alembic.
revision: str = "4d5cd5449049"
down_revision: Union[str, None] = "b15331009e3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="cluster_status_enum",
        new_values=["available", "not_available", "registering", "error", "deleting", "deleted"],
        affected_columns=[TableReference(table_schema="public", table_name="cluster", column_name="status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="cluster_status_enum",
        new_values=["available", "not_available", "registering", "error"],
        affected_columns=[TableReference(table_schema="public", table_name="cluster", column_name="status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
