"""Modified Provider, Cloud model

Revision ID: 5c952f6e6d36
Revises: 7de0638a4964
Create Date: 2025-05-19 04:51:52.545018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c952f6e6d36'
down_revision: Union[str, None] = '7de0638a4964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('/v1/chat/completions', '/v1/completions', '/v1/images/generations', '/v1/audio/transcriptions', '/v1/audio/speech', '/v1/embeddings', '/v1/batch', '/v1/responses', '/v1/rerank', '/v1/moderations', name='model_endpoint_enum').create(op.get_bind())
    op.add_column('cloud_model', sa.Column('supported_endpoints', postgresql.ARRAY(postgresql.ENUM('/v1/chat/completions', '/v1/completions', '/v1/images/generations', '/v1/audio/transcriptions', '/v1/audio/speech', '/v1/embeddings', '/v1/batch', '/v1/responses', '/v1/rerank', '/v1/moderations', name='model_endpoint_enum', create_type=False)), nullable=False))
    op.add_column('provider', sa.Column('is_active', sa.Boolean(), nullable=False, default=True, server_default='true'))
    op.alter_column('provider', 'type',
               existing_type=postgresql.ENUM('nlp_cloud', 'deepinfra', 'anthropic', 'vertex_ai-vision-models', 'vertex_ai-ai21_models', 'cerebras', 'watsonx', 'predibase', 'volcengine', 'clarifai', 'baseten', 'sambanova', 'github', 'petals', 'replicate', 'vertex_ai-chat-models', 'azure_ai', 'perplexity', 'vertex_ai-code-text-models', 'vertex_ai-text-models', 'cohere_chat', 'vertex_ai-embedding-models', 'text-completion-openai', 'groq', 'openai', 'aleph_alpha', 'sagemaker', 'databricks', 'fireworks_ai', 'vertex_ai-anthropic_models', 'vertex_ai-mistral_models', 'voyage', 'vertex_ai-language-models', 'anyscale', 'deepseek', 'vertex_ai-image-models', 'mistral', 'ollama', 'cohere', 'gemini', 'friendliai', 'vertex_ai-code-chat-models', 'azure', 'codestral', 'vertex_ai-llama_models', 'together_ai', 'cloudflare', 'ai21', 'openrouter', 'bedrock', 'text-completion-codestral', 'huggingface', name='credential_type_enum'),
               type_=sa.String(),
               existing_nullable=False)
    sa.Enum('nlp_cloud', 'deepinfra', 'anthropic', 'vertex_ai-vision-models', 'vertex_ai-ai21_models', 'cerebras', 'watsonx', 'predibase', 'volcengine', 'clarifai', 'baseten', 'sambanova', 'github', 'petals', 'replicate', 'vertex_ai-chat-models', 'azure_ai', 'perplexity', 'vertex_ai-code-text-models', 'vertex_ai-text-models', 'cohere_chat', 'vertex_ai-embedding-models', 'text-completion-openai', 'groq', 'openai', 'aleph_alpha', 'sagemaker', 'databricks', 'fireworks_ai', 'vertex_ai-anthropic_models', 'vertex_ai-mistral_models', 'voyage', 'vertex_ai-language-models', 'anyscale', 'deepseek', 'vertex_ai-image-models', 'mistral', 'ollama', 'cohere', 'gemini', 'friendliai', 'vertex_ai-code-chat-models', 'azure', 'codestral', 'vertex_ai-llama_models', 'together_ai', 'cloudflare', 'ai21', 'openrouter', 'bedrock', 'text-completion-codestral', 'huggingface', name='credential_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('nlp_cloud', 'deepinfra', 'anthropic', 'vertex_ai-vision-models', 'vertex_ai-ai21_models', 'cerebras', 'watsonx', 'predibase', 'volcengine', 'clarifai', 'baseten', 'sambanova', 'github', 'petals', 'replicate', 'vertex_ai-chat-models', 'azure_ai', 'perplexity', 'vertex_ai-code-text-models', 'vertex_ai-text-models', 'cohere_chat', 'vertex_ai-embedding-models', 'text-completion-openai', 'groq', 'openai', 'aleph_alpha', 'sagemaker', 'databricks', 'fireworks_ai', 'vertex_ai-anthropic_models', 'vertex_ai-mistral_models', 'voyage', 'vertex_ai-language-models', 'anyscale', 'deepseek', 'vertex_ai-image-models', 'mistral', 'ollama', 'cohere', 'gemini', 'friendliai', 'vertex_ai-code-chat-models', 'azure', 'codestral', 'vertex_ai-llama_models', 'together_ai', 'cloudflare', 'ai21', 'openrouter', 'bedrock', 'text-completion-codestral', 'huggingface', name='credential_type_enum').create(op.get_bind())
    op.alter_column('provider', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('nlp_cloud', 'deepinfra', 'anthropic', 'vertex_ai-vision-models', 'vertex_ai-ai21_models', 'cerebras', 'watsonx', 'predibase', 'volcengine', 'clarifai', 'baseten', 'sambanova', 'github', 'petals', 'replicate', 'vertex_ai-chat-models', 'azure_ai', 'perplexity', 'vertex_ai-code-text-models', 'vertex_ai-text-models', 'cohere_chat', 'vertex_ai-embedding-models', 'text-completion-openai', 'groq', 'openai', 'aleph_alpha', 'sagemaker', 'databricks', 'fireworks_ai', 'vertex_ai-anthropic_models', 'vertex_ai-mistral_models', 'voyage', 'vertex_ai-language-models', 'anyscale', 'deepseek', 'vertex_ai-image-models', 'mistral', 'ollama', 'cohere', 'gemini', 'friendliai', 'vertex_ai-code-chat-models', 'azure', 'codestral', 'vertex_ai-llama_models', 'together_ai', 'cloudflare', 'ai21', 'openrouter', 'bedrock', 'text-completion-codestral', 'huggingface', name='credential_type_enum'),
               existing_nullable=False)
    op.drop_column('provider', 'is_active')
    op.drop_column('cloud_model', 'supported_endpoints')
    sa.Enum('/v1/chat/completions', '/v1/completions', '/v1/images/generations', '/v1/audio/transcriptions', '/v1/audio/speech', '/v1/embeddings', '/v1/batch', '/v1/responses', '/v1/rerank', '/v1/moderations', name='model_endpoint_enum').drop(op.get_bind())
    # ### end Alembic commands ###
