"""Model Table Update.

Revision ID: 5dc1d24e7b7e
Revises: e30d6bcba1dc
Create Date: 2025-01-21 04:53:03.489660

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "5dc1d24e7b7e"
down_revision: Union[str, None] = "e30d6bcba1dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model",
        "base_model",
        type_=postgresql.ARRAY(sa.String()),
        existing_type=sa.String(),
        nullable=True,
        postgresql_using="CASE WHEN base_model IS NULL THEN NULL ELSE array[base_model] END::character varying[]",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model",
        "base_model",
        type_=sa.String(),
        existing_type=postgresql.ARRAY(sa.String()),
        nullable=True,
        postgresql_using="CASE WHEN base_model IS NULL THEN NULL ELSE base_model[1] END::character varying",
    )
    # ### end Alembic commands ###
