"""make cluster_id optional in endpoints

Revision ID: 604ac2c7b0da
Revises: 5ebb7b813ad4
Create Date: 2025-07-17 14:27:48.948643

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "604ac2c7b0da"
down_revision: Union[str, None] = "5ebb7b813ad4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("endpoint", "cluster_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("endpoint", "bud_cluster_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("endpoint", "cluster_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("endpoint", "bud_cluster_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
