"""Updated Endpoint Table.

Revision ID: 64e788fd946c
Revises: 919ebf0fe343
Create Date: 2024-11-29 03:04:06.089062

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "64e788fd946c"
down_revision: Union[str, None] = "919ebf0fe343"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoint", sa.Column("credential_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_endpoint_credential_id_proprietary_credential"),
        "endpoint",
        "proprietary_credential",
        ["credential_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_endpoint_credential_id_proprietary_credential"), "endpoint", type_="foreignkey")
    op.drop_column("endpoint", "credential_id")
    # ### end Alembic commands ###
