"""Updated Endpoint Status.

Revision ID: 68f026ad7360
Revises: 4d5cd5449049
Create Date: 2024-12-16 17:19:08.344175

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference


# revision identifiers, used by Alembic.
revision: str = "68f026ad7360"
down_revision: Union[str, None] = "4d5cd5449049"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="endpoint_status_enum",
        new_values=["running", "failure", "deploying", "unhealthy", "deleting", "deleted"],
        affected_columns=[TableReference(table_schema="public", table_name="endpoint", column_name="status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="endpoint_status_enum",
        new_values=["running", "failure", "deploying", "unhealthy", "deleting"],
        affected_columns=[TableReference(table_schema="public", table_name="endpoint", column_name="status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
