"""Update endpoint table.

Revision ID: 6bd72384f8ba
Revises: 1a20ca43ac69
Create Date: 2025-01-12 12:53:55.092197

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6bd72384f8ba"
down_revision: Union[str, None] = "1a20ca43ac69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoint", sa.Column("total_replicas", sa.Integer(), nullable=False))
    op.add_column("endpoint", sa.Column("number_of_nodes", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("endpoint", "number_of_nodes")
    op.drop_column("endpoint", "total_replicas")
    # ### end Alembic commands ###
