"""add credentails and permissions.

Revision ID: 6cf9d37da8a5
Revises: 28422b983323
Create Date: 2025-03-19 15:00:39.288952

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6cf9d37da8a5"
down_revision: Union[str, None] = "28422b983323"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_permission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("auth_id", sa.Uuid(), nullable=False),
        sa.Column("scopes", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name=op.f("fk_project_permission_project_id_project"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_project_permission_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_permission")),
    )
    # op.add_column('cluster', sa.Column('total_nodes', sa.Integer(), nullable=False))
    # op.add_column("cluster", sa.Column("available_nodes", sa.Integer(), nullable=False))
    # op.add_column("endpoint", sa.Column("node_list", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("proprietary_credential", sa.Column("provider_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        op.f("fk_proprietary_credential_provider_id_provider"),
        "proprietary_credential",
        "provider",
        ["provider_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_proprietary_credential_provider_id_provider"), "proprietary_credential", type_="foreignkey"
    )
    op.drop_column("proprietary_credential", "provider_id")
    op.drop_column("endpoint", "node_list")
    op.drop_column("cluster", "available_nodes")
    op.drop_column("cluster", "total_nodes")
    op.drop_table("project_permission")
    # ### end Alembic commands ###
