"""Added Deploy Config In Endpoint.

Revision ID: 6f3f373ce6b2
Revises: 6bd72384f8ba
Create Date: 2025-01-19 03:47:19.766794

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "6f3f373ce6b2"
down_revision: Union[str, None] = "6bd72384f8ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoint", sa.Column("deployment_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("endpoint", "deployment_config")
    # ### end Alembic commands ###
