"""Added Workflow, Step.

Revision ID: 73ed9f8ea677
Revises: e7ae8abbf8f3
Create Date: 2024-10-28 01:08:08.603863

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "73ed9f8ea677"
down_revision: Union[str, None] = "e7ae8abbf8f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.Enum("in_progress", "completed", "failed", name="workflow_status_enum"), nullable=False
        ),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("total_steps", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name=op.f("fk_workflow_created_by_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow")),
    )
    op.create_index(op.f("ix_workflow_created_by"), "workflow", ["created_by"], unique=False)
    op.create_table(
        "workflow_step",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflow.id"], name=op.f("fk_workflow_step_workflow_id_workflow")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_step")),
    )
    op.create_index(op.f("ix_workflow_step_workflow_id"), "workflow_step", ["workflow_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_step_workflow_id"), table_name="workflow_step")
    op.drop_table("workflow_step")
    op.drop_index(op.f("ix_workflow_created_by"), table_name="workflow")
    op.drop_table("workflow")
    # ### end Alembic commands ###
