"""updated license table

Revision ID: 7c3328919458
Revises: 64e788fd946c
Create Date: 2024-12-05 10:36:00.533114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c3328919458"
down_revision: Union[str, None] = "64e788fd946c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_licenses", sa.Column("url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_licenses", "url")
    # ### end Alembic commands ###
