"""Removed license datatype.

Revision ID: 7de0638a4964
Revises: 80ed68fa65df
Create Date: 2025-05-06 08:35:13.092125

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "7de0638a4964"
down_revision: Union[str, None] = "80ed68fa65df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_licenses", "data_type")
    sa.Enum("url", "minio", name="model_license_object_type_enum").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("url", "minio", name="model_license_object_type_enum").create(op.get_bind())
    op.add_column(
        "model_licenses",
        sa.Column(
            "data_type",
            postgresql.ENUM("url", "minio", name="model_license_object_type_enum", create_type=False),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
