"""Added recommended cluster table

Revision ID: 7e9b3e813931
Revises: e5538df6a487
Create Date: 2025-03-23 12:42:57.316769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e9b3e813931'
down_revision: Union[str, None] = 'e5538df6a487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('cpu', 'gpu', 'hpu', name='cluster_hardware_type_enum').create(op.get_bind())
    op.create_table('model_cluster_recommended',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('hardware_type', postgresql.ENUM('cpu', 'gpu', 'hpu', name='cluster_hardware_type_enum', create_type=False), nullable=False),
    sa.Column('cost_per_million_tokens', sa.Float(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], name=op.f('fk_model_cluster_recommended_cluster_id_cluster')),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_model_cluster_recommended_model_id_model')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_cluster_recommended'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_cluster_recommended')
    sa.Enum('cpu', 'gpu', 'hpu', name='cluster_hardware_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
