"""Updated Model Template Type Datatype.

Revision ID: 80ed68fa65df
Revises: ae9f2a5b92ba
Create Date: 2025-04-26 06:17:12.359959

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "80ed68fa65df"
down_revision: Union[str, None] = "ae9f2a5b92ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model_template",
        "template_type",
        existing_type=postgresql.ENUM(
            "summarization",
            "chat",
            "question_answering",
            "rag",
            "code_gen",
            "code_translation",
            "entity_extraction",
            "sentiment_analysis",
            "document_analysis",
            "other",
            name="template_type_enum",
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_constraint("uq_model_template_template_type", "model_template", type_="unique")
    sa.Enum(
        "summarization",
        "chat",
        "question_answering",
        "rag",
        "code_gen",
        "code_translation",
        "entity_extraction",
        "sentiment_analysis",
        "document_analysis",
        "other",
        name="template_type_enum",
    ).drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "summarization",
        "chat",
        "question_answering",
        "rag",
        "code_gen",
        "code_translation",
        "entity_extraction",
        "sentiment_analysis",
        "document_analysis",
        "other",
        name="template_type_enum",
    ).create(op.get_bind())
    op.create_unique_constraint("uq_model_template_template_type", "model_template", ["template_type"])
    op.alter_column(
        "model_template",
        "template_type",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "summarization",
            "chat",
            "question_answering",
            "rag",
            "code_gen",
            "code_translation",
            "entity_extraction",
            "sentiment_analysis",
            "document_analysis",
            "other",
            name="template_type_enum",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
