"""Added Model Table.

Revision ID: 8611a4c07457
Revises:
Create Date: 2024-10-24 18:14:56.715599

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "8611a4c07457"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tasks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("model_size", sa.BigInteger(), nullable=True),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column("github_url", sa.String(), nullable=True),
        sa.Column("huggingface_url", sa.String(), nullable=True),
        sa.Column("website_url", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "modality",
            sa.Enum("llm", "image", "embedding", "text_to_speech", "speech_to_text", name="modality_enum"),
            nullable=False,
        ),
        sa.Column("type", sa.Enum("pretrained", "chat", "codegen", name="model_type_enum"), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column(
            "provider_type",
            sa.Enum("cloud_model", "hugging_face", "url", "disk", name="model_provider_type_enum"),
            nullable=False,
        ),
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model")
    # ### end Alembic commands ###
