"""Added Status In Security Scan Table.

Revision ID: 87708bcf2070
Revises: 61d0ff8cf1cd
Create Date: 2024-12-10 08:31:19.223251

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "87708bcf2070"
down_revision: Union[str, None] = "61d0ff8cf1cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("low", "medium", "high", "critical", name="model_security_scan_status_enum").create(op.get_bind())
    op.add_column(
        "model_security_scan_result",
        sa.Column(
            "status",
            postgresql.ENUM(
                "low", "medium", "high", "critical", name="model_security_scan_status_enum", create_type=False
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_security_scan_result", "status")
    sa.Enum("low", "medium", "high", "critical", name="model_security_scan_status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
