"""removed is active from cluster table.

Revision ID: 892c31d1e086
Revises: b2c9ac9ba65b
Create Date: 2024-12-19 09:58:34.806743

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "892c31d1e086"
down_revision: Union[str, None] = "b2c9ac9ba65b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
