"""updated workflow table

Revision ID: 8e1725982376
Revises: 375eb22cb3af
Create Date: 2025-01-23 19:05:03.880683

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8e1725982376"
down_revision: Union[str, None] = "375eb22cb3af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PUBLIC", "INTERNAL", name="visibility_enum").create(op.get_bind())
    op.add_column(
        "workflow",
        sa.Column(
            "visibility",
            postgresql.ENUM("PUBLIC", "INTERNAL", name="visibility_enum", create_type=False),
            nullable=False,
        ),
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="workflow_type_enum",
        new_values=[
            "model_deployment",
            "model_security_scan",
            "cluster_onboarding",
            "cluster_deletion",
            "endpoint_deletion",
            "cloud_model_onboarding",
            "local_model_onboarding",
            "license_faq_fetch",
        ],
        affected_columns=[TableReference(table_schema="public", table_name="workflow", column_name="workflow_type")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="workflow_type_enum",
        new_values=[
            "model_deployment",
            "model_security_scan",
            "cluster_onboarding",
            "cluster_deletion",
            "endpoint_deletion",
            "cloud_model_onboarding",
            "local_model_onboarding",
        ],
        affected_columns=[TableReference(table_schema="public", table_name="workflow", column_name="workflow_type")],
        enum_values_to_rename=[],
    )
    op.drop_column("workflow", "visibility")
    sa.Enum("PUBLIC", "INTERNAL", name="visibility_enum").drop(op.get_bind())
    # ### end Alembic commands ###
