"""Added Cloud Model.

Revision ID: 97795f1e0340
Revises: 73ed9f8ea677
Create Date: 2024-10-28 05:55:59.610125

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "97795f1e0340"
down_revision: Union[str, None] = "73ed9f8ea677"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloud_model",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tasks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("model_size", sa.BigInteger(), nullable=True),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column("github_url", sa.String(), nullable=True),
        sa.Column("huggingface_url", sa.String(), nullable=True),
        sa.Column("website_url", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "modality",
            postgresql.ENUM(
                "llm",
                "image",
                "embedding",
                "text_to_speech",
                "speech_to_text",
                name="modality_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "type",
            postgresql.ENUM("pretrained", "chat", "codegen", name="model_type_enum", create_type=False),
            nullable=True,
        ),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column(
            "provider_type",
            postgresql.ENUM(
                "cloud_model", "hugging_face", "url", "disk", name="model_provider_type_enum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["provider_id"], ["provider.id"], name=op.f("fk_cloud_model_provider_id_provider")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cloud_model")),
    )
    op.alter_column(
        "model",
        "type",
        existing_type=postgresql.ENUM("pretrained", "chat", "codegen", name="model_type_enum", create_type=False),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model",
        "type",
        existing_type=postgresql.ENUM("pretrained", "chat", "codegen", name="model_type_enum", create_type=False),
        nullable=False,
    )
    op.drop_table("cloud_model")
    # ### end Alembic commands ###
