"""updated cloud model with model status

Revision ID: 9e66865a1e1b
Revises: 8d317585f402
Create Date: 2024-12-10 05:47:05.171527

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9e66865a1e1b"
down_revision: Union[str, None] = "8d317585f402"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cloud_model",
        sa.Column(
            "model_status", postgresql.ENUM("active", "deleted", name="status_enum", create_type=False), nullable=False
        ),
    )
    op.drop_column("cloud_model", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cloud_model", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("cloud_model", "model_status")
    # ### end Alembic commands ###
