"""Added data type in model license.

Revision ID: a795bbd26b97
Revises: c628093b72f0
Create Date: 2025-06-02 04:48:58.325027

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "a795bbd26b97"
down_revision: Union[str, None] = "c628093b72f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("url", "minio", name="model_license_object_type_enum").create(op.get_bind())

    # NOTE: In last release of budapp, all urls should be saved as minio object. so we need to set all existing data_type as minio
    op.add_column(
        "model_licenses",
        sa.Column(
            "data_type",
            postgresql.ENUM("url", "minio", name="model_license_object_type_enum", create_type=False),
            nullable=False,
            server_default="minio",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_licenses", "data_type")
    sa.Enum("url", "minio", name="model_license_object_type_enum").drop(op.get_bind())
    # ### end Alembic commands ###
