"""Updated license table

Revision ID: ab1a2a66c589
Revises: 35c352d33c91
Create Date: 2025-04-03 19:12:01.248649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab1a2a66c589'
down_revision: Union[str, None] = '35c352d33c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('url', 'minio', name='model_license_object_type_enum').create(op.get_bind())
    op.add_column('model_licenses', sa.Column('data_type', postgresql.ENUM('url', 'minio', name='model_license_object_type_enum', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_licenses', 'data_type')
    sa.Enum('url', 'minio', name='model_license_object_type_enum').drop(op.get_bind())
    # ### end Alembic commands ###
