"""Updated cloud model.

Revision ID: acb041e05c53
Revises: b2a743972235
Create Date: 2024-11-21 05:24:36.533236

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "acb041e05c53"
down_revision: Union[str, None] = "b2a743972235"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cloud_model", sa.Column("is_present_in_model", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cloud_model", "is_present_in_model")
    # ### end Alembic commands ###
