"""Updated Model Table.

Revision ID: af5cc669f51e
Revises: 1b33efcd5611
Create Date: 2025-01-02 18:41:55.839398

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "af5cc669f51e"
down_revision: Union[str, None] = "1b33efcd5611"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model", sa.Column("model_weights_size", sa.BigInteger(), nullable=True))
    op.add_column("model", sa.Column("kv_cache_size", sa.BigInteger(), nullable=True))
    op.add_column(
        "model", sa.Column("architecture_text_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "model", sa.Column("architecture_vision_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.drop_column("model", "context_length")
    op.drop_column("model", "num_layers")
    op.drop_column("model", "architecture")
    op.drop_column("model", "hidden_size")
    op.drop_column("model", "torch_dtype")
    op.sync_enum_values(
        enum_schema="public",
        enum_name="modality_enum",
        new_values=["llm", "mllm", "image", "embedding", "text_to_speech", "speech_to_text"],
        affected_columns=[
            TableReference(table_schema="public", table_name="cloud_model", column_name="modality"),
            TableReference(table_schema="public", table_name="model", column_name="modality"),
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="modality_enum",
        new_values=["llm", "image", "embedding", "text_to_speech", "speech_to_text"],
        affected_columns=[
            TableReference(table_schema="public", table_name="cloud_model", column_name="modality"),
            TableReference(table_schema="public", table_name="model", column_name="modality"),
        ],
        enum_values_to_rename=[],
    )
    op.add_column("model", sa.Column("torch_dtype", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("model", sa.Column("hidden_size", sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column(
        "model", sa.Column("architecture", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.add_column("model", sa.Column("num_layers", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("model", sa.Column("context_length", sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column("model", "architecture_vision_config")
    op.drop_column("model", "architecture_text_config")
    op.drop_column("model", "kv_cache_size")
    op.drop_column("model", "model_weights_size")
    # ### end Alembic commands ###
