"""Remove replica from endpoint table.

Revision ID: b15331009e3f
Revises: 5352d4677f70
Create Date: 2024-12-13 15:30:28.338183

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b15331009e3f"
down_revision: Union[str, None] = "5352d4677f70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("endpoint", "replicas")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoint", sa.Column("replicas", sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
