"""Added provider table

Revision ID: b24915dd9e7a
Revises: ffb55b8f01fc
Create Date: 2024-10-27 15:15:32.814228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24915dd9e7a'
down_revision: Union[str, None] = 'ffb55b8f01fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('nlp_cloud', 'deepinfra', 'anthropic', 'vertex_ai-vision-models', 'replicate', 'vertex_ai-chat-models', 'azure_ai', 'perplexity', 'vertex_ai-code-text-models', 'vertex_ai-text-models', 'palm', 'cohere_chat', 'vertex_ai-embedding-models', 'text-completion-openai', 'groq', 'openai', 'aleph_alpha', 'sagemaker', 'databricks', 'fireworks_ai', 'vertex_ai-anthropic_models', 'vertex_ai-mistral_models', 'voyage', 'vertex_ai-language-models', 'anyscale', 'deepseek', 'vertex_ai-image-models', 'mistral', 'ollama', 'cohere', 'gemini', 'friendliai', 'vertex_ai-code-chat-models', 'azure', 'codestral', 'vertex_ai-llama_models', 'together_ai', 'cloudflare', 'ai21', 'openrouter', 'bedrock', 'text-completion-codestral', 'huggingface', name='credential_type_enum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider')
    # ### end Alembic commands ###
