"""Modified Workflow Table.

Revision ID: b2c9ac9ba65b
Revises: d92d92c1c90c
Create Date: 2024-12-19 13:30:12.338808

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "b2c9ac9ba65b"
down_revision: Union[str, None] = "d92d92c1c90c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "model_deployment",
        "model_security_scan",
        "cluster_onboarding",
        "cluster_deletion",
        "endpoint_deletion",
        "cloud_model_onboarding",
        "local_model_onboarding",
        name="workflow_type_enum",
    ).create(op.get_bind())
    op.add_column(
        "workflow",
        sa.Column(
            "workflow_type",
            postgresql.ENUM(
                "model_deployment",
                "model_security_scan",
                "cluster_onboarding",
                "cluster_deletion",
                "endpoint_deletion",
                "cloud_model_onboarding",
                "local_model_onboarding",
                name="workflow_type_enum",
                create_type=False,
            ),
            nullable=False,
        ),
    )
    op.add_column("workflow", sa.Column("title", sa.String(), nullable=True))
    op.add_column("workflow", sa.Column("icon", sa.String(), nullable=True))
    op.add_column("workflow", sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow", "progress")
    op.drop_column("workflow", "icon")
    op.drop_column("workflow", "title")
    op.drop_column("workflow", "workflow_type")
    sa.Enum(
        "model_deployment",
        "model_security_scan",
        "cluster_onboarding",
        "cluster_deletion",
        "endpoint_deletion",
        "cloud_model_onboarding",
        "local_model_onboarding",
        name="workflow_type_enum",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
