"""removed icon column from cloudmodel table

Revision ID: bae69001e83c
Revises: 036fd90d4d6b
Create Date: 2024-11-15 10:30:25.972038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae69001e83c'
down_revision: Union[str, None] = '036fd90d4d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_model', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_model', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
