"""added model status in model table

Revision ID: bc228b8963b6
Revises: 64e788fd946c
Create Date: 2024-12-03 10:09:59.042958

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc228b8963b6"
down_revision: Union[str, None] = "64e788fd946c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("active", "deleted", name="status_enum").create(op.get_bind())
    op.add_column(
        "model",
        sa.Column(
            "model_status", postgresql.ENUM("active", "deleted", name="status_enum", create_type=False), nullable=False
        ),
    )
    op.drop_column("model", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("model", "model_status")
    sa.Enum("active", "deleted", name="status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
