"""Modified endpoint table.

Revision ID: bcd1218837d9
Revises: dac83b8cf76f
Create Date: 2024-11-13 14:16:14.672059

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bcd1218837d9"
down_revision: Union[str, None] = "dac83b8cf76f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoint", sa.Column("bud_cluster_id", sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("endpoint", "bud_cluster_id")
    # ### end Alembic commands ###
