"""supported endpoints in endpoint table.

Revision ID: c301ac188f1b
Revises: a795bbd26b97
Create Date: 2025-06-25 13:58:51.465617

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "c301ac188f1b"
down_revision: Union[str, None] = "a795bbd26b97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cloud_model",
        "modality",
        existing_type=postgresql.ARRAY(
            postgresql.ENUM(
                "text_input",
                "text_output",
                "image_input",
                "image_output",
                "audio_input",
                "audio_output",
                name="modality_enum",
            )
        ),
        nullable=False,
    )
    op.alter_column(
        "cloud_model",
        "supported_endpoints",
        existing_type=postgresql.ARRAY(
            postgresql.ENUM(
                "/v1/chat/completions",
                "/v1/completions",
                "/v1/images/generations",
                "/v1/audio/transcriptions",
                "/v1/audio/speech",
                "/v1/embeddings",
                "/v1/batch",
                "/v1/responses",
                "/v1/rerank",
                "/v1/moderations",
                name="model_endpoint_enum",
            )
        ),
        nullable=False,
    )
    # First add column as nullable
    op.add_column(
        "endpoint",
        sa.Column(
            "supported_endpoints",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "/v1/chat/completions",
                    "/v1/completions",
                    "/v1/images/generations",
                    "/v1/audio/transcriptions",
                    "/v1/audio/speech",
                    "/v1/embeddings",
                    "/v1/batch",
                    "/v1/responses",
                    "/v1/rerank",
                    "/v1/moderations",
                    name="model_endpoint_enum",
                    create_type=False,
                )
            ),
            nullable=True,
        ),
    )

    # Set default value for existing rows
    op.execute(
        "UPDATE endpoint SET supported_endpoints = ARRAY['/v1/chat/completions']::model_endpoint_enum[] WHERE supported_endpoints IS NULL"
    )

    # Now make it non-nullable
    op.alter_column("endpoint", "supported_endpoints", nullable=False)

    op.alter_column(
        "model",
        "modality",
        existing_type=postgresql.ARRAY(
            postgresql.ENUM(
                "text_input",
                "text_output",
                "image_input",
                "image_output",
                "audio_input",
                "audio_output",
                name="modality_enum",
            )
        ),
        nullable=False,
    )
    op.alter_column(
        "model",
        "supported_endpoints",
        existing_type=postgresql.ARRAY(
            postgresql.ENUM(
                "/v1/chat/completions",
                "/v1/completions",
                "/v1/images/generations",
                "/v1/audio/transcriptions",
                "/v1/audio/speech",
                "/v1/embeddings",
                "/v1/batch",
                "/v1/responses",
                "/v1/rerank",
                "/v1/moderations",
                name="model_endpoint_enum",
            )
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model",
        "supported_endpoints",
        existing_type=postgresql.ARRAY(
            postgresql.ENUM(
                "/v1/chat/completions",
                "/v1/completions",
                "/v1/images/generations",
                "/v1/audio/transcriptions",
                "/v1/audio/speech",
                "/v1/embeddings",
                "/v1/batch",
                "/v1/responses",
                "/v1/rerank",
                "/v1/moderations",
                name="model_endpoint_enum",
            )
        ),
        nullable=True,
    )
    op.alter_column(
        "model",
        "modality",
        existing_type=postgresql.ARRAY(
            postgresql.ENUM(
                "text_input",
                "text_output",
                "image_input",
                "image_output",
                "audio_input",
                "audio_output",
                name="modality_enum",
            )
        ),
        nullable=True,
    )
    op.drop_column("endpoint", "supported_endpoints")
    op.alter_column(
        "cloud_model",
        "supported_endpoints",
        existing_type=postgresql.ARRAY(
            postgresql.ENUM(
                "/v1/chat/completions",
                "/v1/completions",
                "/v1/images/generations",
                "/v1/audio/transcriptions",
                "/v1/audio/speech",
                "/v1/embeddings",
                "/v1/batch",
                "/v1/responses",
                "/v1/rerank",
                "/v1/moderations",
                name="model_endpoint_enum",
            )
        ),
        nullable=True,
    )
    op.alter_column(
        "cloud_model",
        "modality",
        existing_type=postgresql.ARRAY(
            postgresql.ENUM(
                "text_input",
                "text_output",
                "image_input",
                "image_output",
                "audio_input",
                "audio_output",
                name="modality_enum",
            )
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
