"""added status to model and cloud model table.

Revision ID: cbbdd257bedd
Revises: 68f026ad7360
Create Date: 2024-12-17 09:16:24.851050

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "cbbdd257bedd"
down_revision: Union[str, None] = "68f026ad7360"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("active", "deleted", name="cloud_model_status_enum").create(op.get_bind())
    sa.Enum("active", "deleted", name="model_status_enum").create(op.get_bind())
    op.add_column(
        "cloud_model",
        sa.Column(
            "status",
            postgresql.ENUM("active", "deleted", name="cloud_model_status_enum", create_type=False),
            nullable=False,
        ),
    )
    op.drop_column("cloud_model", "is_active")
    op.add_column(
        "model",
        sa.Column(
            "status", postgresql.ENUM("active", "deleted", name="model_status_enum", create_type=False), nullable=False
        ),
    )
    op.drop_column("model", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("model", "status")
    op.add_column("cloud_model", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("cloud_model", "status")
    sa.Enum("active", "deleted", name="model_status_enum").drop(op.get_bind())
    sa.Enum("active", "deleted", name="cloud_model_status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
