"""Added Icon Model.

Revision ID: d337aa91475f
Revises: 97795f1e0340
Create Date: 2024-11-01 03:11:51.288688

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d337aa91475f"
down_revision: Union[str, None] = "97795f1e0340"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "icon",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_icon")),
        sa.UniqueConstraint("file_path", name=op.f("uq_icon_file_path")),
    )
    op.create_index(op.f("ix_icon_category"), "icon", ["category"], unique=False)
    op.create_index(op.f("ix_icon_name"), "icon", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_icon_name"), table_name="icon")
    op.drop_index(op.f("ix_icon_category"), table_name="icon")
    op.drop_table("icon")
    # ### end Alembic commands ###
