"""added icon to cluster table.

Revision ID: d5d05bae8c2c
Revises: bcd1218837d9
Create Date: 2024-11-13 16:52:43.088313

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d5d05bae8c2c"
down_revision: Union[str, None] = "bcd1218837d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster", sa.Column("icon", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster", "icon")
    # ### end Alembic commands ###
