"""removed is active from user table.

Revision ID: da9cd25f9dcc
Revises: e3ac5a852b2c
Create Date: 2024-12-23 06:33:11.002691

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference


# revision identifiers, used by Alembic.
revision: str = "da9cd25f9dcc"
down_revision: Union[str, None] = "e3ac5a852b2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_active")
    op.sync_enum_values(
        enum_schema="public",
        enum_name="user_status_enum",
        new_values=["active", "deleted", "invited"],
        affected_columns=[TableReference(table_schema="public", table_name="user", column_name="status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="user_status_enum",
        new_values=["active", "inactive", "invited"],
        affected_columns=[TableReference(table_schema="public", table_name="user", column_name="status")],
        enum_values_to_rename=[],
    )
    op.add_column("user", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
