"""updated notes table

Revision ID: e32cfcc9b705
Revises: f94d2a607eb9
Create Date: 2025-03-05 09:59:36.336899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e32cfcc9b705"
down_revision: Union[str, None] = "f94d2a607eb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("user_id", sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes", "user_id")
    # ### end Alembic commands ###
