"""added model configuration to endpoint table.

Revision ID: e3ac5a852b2c
Revises: 0c7fdc4b7072
Create Date: 2024-12-24 05:44:36.018289

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "e3ac5a852b2c"
down_revision: Union[str, None] = "0c7fdc4b7072"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoint", sa.Column("model_configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("endpoint", "model_configuration")
    # ### end Alembic commands ###
