"""Added missing migration.

Revision ID: e63b762b3386
Revises: 2b3ddb265bd7
Create Date: 2025-03-25 06:18:31.353789

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "e63b762b3386"
down_revision: Union[str, None] = "2b3ddb265bd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloud_providers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("logo_url", sa.String(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("schema_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unique_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unique_id"),
    )
    op.create_table(
        "cloud_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("credential", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("credential_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["provider_id"], ["cloud_providers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("cluster", sa.Column("cluster_type", sa.String(), nullable=False))
    op.add_column("cluster", sa.Column("cloud_provider_id", sa.Uuid(), nullable=True))
    op.add_column("cluster", sa.Column("credential_id", sa.Uuid(), nullable=True))
    op.add_column("cluster", sa.Column("region", sa.String(), nullable=True))
    op.alter_column("cluster", "ingress_url", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("success", "failed", "processing", name="benchmark_status_enum").create(op.get_bind())
    op.alter_column("cluster", "ingress_url", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("cluster", "region")
    op.drop_column("cluster", "credential_id")
    op.drop_column("cluster", "cloud_provider_id")
    op.drop_column("cluster", "cluster_type")
    op.drop_table("cloud_credentials")
    op.drop_table("cloud_providers")
    # ### end Alembic commands ###
