"""updated cloud model table.

Revision ID: e9f810852a5d
Revises: 33225f9cc055
Create Date: 2025-03-18 03:46:28.169177

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "e9f810852a5d"
down_revision: Union[str, None] = "33225f9cc055"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cloud_model", sa.Column("max_input_tokens", sa.Integer(), nullable=True))
    op.add_column("cloud_model", sa.Column("input_cost", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("cloud_model", sa.Column("output_cost", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cloud_model", "output_cost")
    op.drop_column("cloud_model", "input_cost")
    op.drop_column("cloud_model", "max_input_tokens")
    # ### end Alembic commands ###
