"""message

Revision ID: f05be458b662
Revises: f94d2a607eb9
Create Date: 2025-03-07 09:17:48.474540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'f05be458b662'
down_revision: Union[str, None] = 'f94d2a607eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='workflow_type_enum',
        new_values=['model_deployment', 'model_security_scan', 'cluster_onboarding', 'cluster_deletion', 'endpoint_deletion', 'endpoint_worker_deletion', 'cloud_model_onboarding', 'local_model_onboarding', 'add_worker_to_endpoint', 'license_faq_fetch', 'local_model_quantization'],
        affected_columns=[TableReference(table_schema='public', table_name='workflow', column_name='workflow_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='workflow_type_enum',
        new_values=['model_deployment', 'model_security_scan', 'cluster_onboarding', 'cluster_deletion', 'endpoint_deletion', 'endpoint_worker_deletion', 'cloud_model_onboarding', 'local_model_onboarding', 'add_worker_to_endpoint', 'license_faq_fetch'],
        affected_columns=[TableReference(table_schema='public', table_name='workflow', column_name='workflow_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
