"""updated chat setting table

Revision ID: f3727a064c4b
Revises: 1003edcadb5d
Create Date: 2025-03-03 12:27:44.469922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3727a064c4b"
down_revision: Union[str, None] = "1003edcadb5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_settings", sa.Column("name", sa.String(), nullable=False))
    op.add_column("chat_settings", sa.Column("system_prompt", sa.String(), nullable=True))
    op.add_column("chat_settings", sa.Column("temperature", sa.Float(), nullable=False))
    op.add_column("chat_settings", sa.Column("limit_sequence_length", sa.Boolean(), nullable=False))
    op.add_column("chat_settings", sa.Column("sequence_length", sa.Integer(), nullable=True))
    op.add_column("chat_settings", sa.Column("context_overflow_policy", sa.String(), nullable=False))
    op.add_column("chat_settings", sa.Column("stop_strings", sa.ARRAY(sa.String()), nullable=True))
    op.add_column("chat_settings", sa.Column("topKSampling", sa.Float(), nullable=True))
    op.add_column("chat_settings", sa.Column("repeatPenalty", sa.Float(), nullable=True))
    op.add_column("chat_settings", sa.Column("topPSampling", sa.Float(), nullable=True))
    op.add_column("chat_settings", sa.Column("minPSampling", sa.Float(), nullable=True))
    op.add_column("chat_settings", sa.Column("structured_json_schema", sa.JSON(), nullable=True))
    op.drop_column("chat_settings", "preset_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_settings", sa.Column("preset_name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("chat_settings", "structured_json_schema")
    op.drop_column("chat_settings", "minPSampling")
    op.drop_column("chat_settings", "topPSampling")
    op.drop_column("chat_settings", "repeatPenalty")
    op.drop_column("chat_settings", "topKSampling")
    op.drop_column("chat_settings", "stop_strings")
    op.drop_column("chat_settings", "context_overflow_policy")
    op.drop_column("chat_settings", "sequence_length")
    op.drop_column("chat_settings", "limit_sequence_length")
    op.drop_column("chat_settings", "temperature")
    op.drop_column("chat_settings", "system_prompt")
    op.drop_column("chat_settings", "name")
    # ### end Alembic commands ###
