"""Removed model type.

Revision ID: f759834112e2
Revises: d337aa91475f
Create Date: 2024-11-01 05:27:40.482128

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "f759834112e2"
down_revision: Union[str, None] = "d337aa91475f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cloud_model", "type")
    op.drop_column("model", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model",
        sa.Column(
            "type",
            postgresql.ENUM("pretrained", "chat", "codegen", name="model_type_enum"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "cloud_model",
        sa.Column(
            "type",
            postgresql.ENUM("pretrained", "chat", "codegen", name="model_type_enum"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
