"""added icon field in cluster table

Revision ID: f85337e4e652
Revises: dac83b8cf76f
Create Date: 2024-11-13 10:51:53.621480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85337e4e652'
down_revision: Union[str, None] = 'dac83b8cf76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('icon', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster', 'icon')
    # ### end Alembic commands ###
