"""updated chat setting table.

Revision ID: f94d2a607eb9
Revises: 1003edcadb5d
Create Date: 2025-03-05 04:51:50.958104

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "f94d2a607eb9"
down_revision: Union[str, None] = "1003edcadb5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_settings", sa.Column("name", sa.String(), nullable=False))
    op.add_column("chat_settings", sa.Column("system_prompt", sa.String(), nullable=True))
    op.add_column("chat_settings", sa.Column("temperature", sa.Float(), nullable=False))
    op.add_column("chat_settings", sa.Column("limit_response_length", sa.Boolean(), nullable=False))
    op.add_column("chat_settings", sa.Column("sequence_length", sa.Integer(), nullable=True))
    op.add_column("chat_settings", sa.Column("context_overflow_policy", sa.String(), nullable=True))
    op.add_column("chat_settings", sa.Column("stop_strings", postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column("chat_settings", sa.Column("top_k_sampling", sa.Integer(), nullable=True))
    op.add_column("chat_settings", sa.Column("repeat_penalty", sa.Float(), nullable=True))
    op.add_column("chat_settings", sa.Column("top_p_sampling", sa.Float(), nullable=True))
    op.add_column("chat_settings", sa.Column("min_p_sampling", sa.Float(), nullable=True))
    op.add_column(
        "chat_settings", sa.Column("structured_json_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.drop_column("chat_settings", "preset_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_settings", sa.Column("preset_name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("chat_settings", "structured_json_schema")
    op.drop_column("chat_settings", "min_p_sampling")
    op.drop_column("chat_settings", "top_p_sampling")
    op.drop_column("chat_settings", "repeat_penalty")
    op.drop_column("chat_settings", "top_k_sampling")
    op.drop_column("chat_settings", "stop_strings")
    op.drop_column("chat_settings", "context_overflow_policy")
    op.drop_column("chat_settings", "sequence_length")
    op.drop_column("chat_settings", "limit_response_length")
    op.drop_column("chat_settings", "temperature")
    op.drop_column("chat_settings", "system_prompt")
    op.drop_column("chat_settings", "name")
    # ### end Alembic commands ###
