"""Modified model table.

Revision ID: ffb55b8f01fc
Revises: e2d7e5f38d3c
Create Date: 2024-10-27 12:50:50.443071

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ffb55b8f01fc"
down_revision: Union[str, None] = "e2d7e5f38d3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("model", "author", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("model", "author", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
