"""Make cluster_id optional in endpoint table

Revision ID: make_cluster_id_optional_in_endpoint
Revises: ffb55b8f01fc
Create Date: 2025-01-17 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "make_cluster_id_optional_in_endpoint"
down_revision: Union[str, None] = "ffb55b8f01fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make cluster_id nullable in endpoint table
    op.alter_column("endpoint", "cluster_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make cluster_id non-nullable in endpoint table
    # Note: This will fail if there are NULL values in the column
    op.alter_column("endpoint", "cluster_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
